server.port=8080
logging.level.ru.yandex.practicum.filmorate=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.boot=TRACE
logging.level.org.apache.catalina=DEBUG
logging.level.org.apache.tomcat=DEBUG